<?php

/**
 * @file
 * Contains docmagic_migrate_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function docmagic_migrate_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the docmagic_migrate_views module.
    case 'help.page.docmagic_migrate_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper code to ease DocMagic site migration from Drupal 6 to Drupal 8') . '</p>';
      return $output;

    default:
  }
}
