<?php

/**
 * @file
 * Contains docmagic_cas.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function docmagic_cas_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the docmagic_cas module.
    case 'help.page.docmagic_cas':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DocMagic CAS') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function docmagic_cas_form_cas_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    $config = \Drupal::configFactory()->get('cas.settings');

    $cas_trial_roles = $config->get('user_accounts.cas_trial_roles') ?: array();
    $cas_compliance_roles = $config->get('user_accounts.cas_compliance_roles') ?: array();
    $cas_compliance_basic_roles = $config->get('user_accounts.cas_compliance_basic_roles') ?: array();

    $roles = user_role_names(TRUE);
    unset($roles[\Drupal\user\RoleInterface::AUTHENTICATED_ID]);

    $form['user_accounts']['cas_trial_roles'] = array(
        '#type' => 'select',
        '#multiple' => TRUE,
        '#title' => t('Auto-assign trial users to the role(s)'),
        '#description' => t('This value can be used to establish a role automatically for all CAS users with compliance setting.'),
        '#default_value' => $cas_trial_roles,
        '#options' => $roles,
        '#states' => array(
            'invisible' => array(
                'input[name="user_accounts[auto_assigned_roles_enable]"]' => array('checked' => FALSE),
            ),
        ),
    );

    $form['user_accounts']['cas_compliance_roles'] = array(
        '#type' => 'select',
        '#multiple' => TRUE,
        '#title' => t('Auto-assign compliance users to the role(s)'),
        '#description' => t('This value can be used to establish a role automatically for all CAS users with compliance setting.'),
        '#default_value' => $cas_compliance_roles,
        '#options' => $roles,
        '#states' => array(
            'invisible' => array(
                'input[name="user_accounts[auto_assigned_roles_enable]"]' => array('checked' => FALSE),
            ),
        ),
    );

    $form['user_accounts']['cas_compliance_basic_roles'] = array(
        '#type' => 'select',
        '#multiple' => TRUE,
        '#title' => t('Auto-assign compliance basic users to the role(s)'),
        '#description' => t('This value can be used to establish a role automatically for all CAS users with compliance basic setting.'),
        '#default_value' => $cas_compliance_basic_roles,
        '#options' => $roles,
        '#states' => array(
            'invisible' => array(
                'input[name="user_accounts[auto_assigned_roles_enable]"]' => array('checked' => FALSE),
            ),
        ),
    );

    $form['#submit'][] = 'docmagic_cas_form_cas_settings_callback';
}

function docmagic_cas_form_cas_settings_callback(array $form, \Drupal\Core\Form\FormStateInterface &$form_state)
{
    $config = \Drupal::configFactory()->getEditable('cas.settings');

    $cas_trial_roles = array();
    $cas_compliance_roles = array();
    $cas_compliance_basic_roles = array();

    if ($form_state->getValue(['user_accounts', 'auto_assigned_roles_enable'])) {
        $cas_trial_roles = array_keys($form_state->getValue(['user_accounts', 'cas_trial_roles']));
        $cas_compliance_roles = array_keys($form_state->getValue(['user_accounts', 'cas_compliance_roles']));
        $cas_compliance_basic_roles = array_keys($form_state->getValue(['user_accounts', 'cas_compliance_basic_roles']));
    }

    $config
        ->set('user_accounts.cas_trial_roles', $cas_trial_roles)
        ->set('user_accounts.cas_compliance_roles', $cas_compliance_roles)
        ->set('user_accounts.cas_compliance_basic_roles', $cas_compliance_basic_roles);

    $config->save();
}
