<?php

/**
 * @file
 * Contains docmagic_compliance_newsletter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function docmagic_compliance_newsletter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the docmagic_compliance_newsletter module.
    case 'help.page.docmagic_compliance_newsletter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Compliance Newsletter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function docmagic_compliance_newsletter_form_node_simplenews_issue_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $form['#attached']['library'][] = 'clipboardjs/drupal';

    $clipboardjsModulePath = base_path().drupal_get_path('module', 'clipboardjs');
    $id = 'edit-body-0-value';
    $alertStyle = 'alert';
    $alertText = 'The HTML Content has been copied to the Clipboard';
    $label = 'Copy HTML Content to Clipboard';
    $alt = 'Copy';
    $height = '20';
    $width = '20';

    $buttonHtml = <<<EOF
<script>
function prepareClipboardText(element) {
    var selector = jQuery(element).data('clipboardTarget');
    jQuery(selector).css({'position': 'absolute', 'left': '-9999px', 'visibility': 'visible'}).show();
}
</script>
<a class="clipboardjs-button" data-clipboard-alert="{$alertStyle}" data-clipboard-alert-text="{$alertText}" data-clipboard-target="#{$id}" onClick="prepareClipboardText(this)">
  <img src="{$clipboardjsModulePath}/images/clippy.svg" alt="{$alt}" height="{$height}" width="{$width}" />
  <span>{$label}</span>
</a>
EOF;

    $form['body']['#prefix'] = \Drupal\Core\Render\Markup::create($buttonHtml);
}

/**
 * Implements hook_library_info_alter().
 */
function docmagic_compliance_newsletter_library_info_alter(&$libraries, $extension) {
    if ('clipboardjs' == $extension) {
        if (isset($libraries['drupal'])) {
            $libraries['drupal']['header'] = true;
        }
        if (isset($libraries['clipboardjs'])) {
            $path = 'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/'.$libraries['clipboardjs']['version'].'/clipboard.min.js';
            $libraries['clipboardjs']['js'] = array(
                $path => array(
                    'external' => true,
                    'minified' => true,
                ),
            );
        }
    }
}
